version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      # - ./uploads:/app/uploads
      # - ./uploads/fakeprofilephotos:/app/fakephotos
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/matcha_app
      - SEED_FAKE_PROFILES=${SEED_FAKE_PROFILES}
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - development
      - production

  frontend:
    build:
      context: ./frontend
    ports:
      - "3002:80"
    profiles:
      - production

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm start
    profiles:
      - development

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: matcha_app
    volumes:
      - db_data:/var/lib/postgresql/data
    profiles:
      - development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    profiles:
      - production
  
volumes:
  db_data: